CREATE TABLE STUDENTS (
    STUDENT_ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    GENDER VARCHAR2(10),
    DOB DATE,
    CATEGORY VARCHAR2(10),

    STATE VARCHAR2(50),
    CITY VARCHAR2(50),
    PINCODE VARCHAR2(10),

    PHYSICS NUMBER,
    CHEMISTRY NUMBER,
    MATHS NUMBER,
    TOTAL NUMBER,
    PERCENTAGE NUMBER,

    JEE_SCORE NUMBER,
    CET_SCORE NUMBER,

    SCHOOL_NAME VARCHAR2(100),
    YEAR_PASSING NUMBER,
    BOARD VARCHAR2(50),

    ADDRESS VARCHAR2(200),
    GUARDIAN_NAME VARCHAR2(100),
    GUARDIAN_PHONE VARCHAR2(20),

    PREFERRED_BRANCH VARCHAR2(100),
    REMARKS VARCHAR2(200)
);